# Generated by Django 2.1.15 on 2021-09-03 22:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_auto_20210903_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='table_capacity',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(12), django.core.validators.MinValueValidator(1)]),
        ),
    ]
